server {
    listen 127.0.0.1:8080;
    listen 8081;
    server_name 127.0.0.1 localhost site1.com site2.com;
    client_max_body_size 1m;
    error_page 404 400 403 405 evo_test/error.html;
    root ../evo/www;

    location / {
        allow_methods GET HEAD;
    }

    location /klasor1 {
        root ../evo/www/klasor1;
        allow_methods GET;
        index page.html;
    }

    location /autoindex_on {
        root ../evo/www/assets;
        autoindex on;
    }

    location /autoindex_off {
        root ../evo/www/assets;
        autoindex off;
    }

    location /eski_sayfa {
        return 301 http://google.com;
    }

    location /post_test {
        allow_methods POST;
        upload_dir ../evo/www/uploads;
    }

    location /upload {
        allow_methods POST;
        client_max_body_size 16m;
        upload_dir ../evo/www/uploads;
    }

    location /uploads {
        root ../evo/www/uploads;
        allow_methods GET DELETE;
    }

}
