services:
  mariadb:
    build:
      context: ./requirements/mariadb
      dockerfile: Dockerfile
    container_name: mariadb
    restart: always
    networks:
      - inception_network
    volumes:
      - mariadb_volume:/var/lib/mysql
    secrets:
      - db_password
      - db_root_password
    env_file:
      - .env

  wordpress:
    build:
      context: ./requirements/wordpress
      dockerfile: Dockerfile_bonus
    container_name: wordpress
    restart: always
    networks:
      - inception_network
    volumes:
      - wordpress_volume:/var/www/html
    secrets:
      - db_password
      - credentials
    env_file:
      - .env

  nginx:
    build:
      context: ./requirements/nginx
      dockerfile: Dockerfile
    container_name: nginx
    restart: always
    ports:
      - "443:443"
    networks:
      - inception_network
    volumes:
      - wordpress_volume:/var/www/html
    env_file:
      - .env

  redis:
    build:
      context: ./requirements/bonus/redis
      dockerfile: Dockerfile
    container_name: redis
    restart: always
    env_file:
      - .env
    networks:
      - inception_network

  ftp:
    build:
      context: ./requirements/bonus/ftp
      dockerfile: Dockerfile
    container_name: ftp
    restart: always
    env_file:
      - .env_bonus
    ports:
      - "21:21"
    volumes:
      - wordpress_volume:/var/www/html
    secrets:
      - ftp_password
    networks:
      - inception_network

  adminer:
    build:
      context: ./requirements/bonus/adminer
      dockerfile: Dockerfile
    container_name: adminer
    restart: always
    ports:
      - "8080:8080"
    networks:
      - inception_network

  static_site:
    build:
      context: ./requirements/bonus/static_site
      dockerfile: Dockerfile
    container_name: static_site
    restart: always
    ports:
      - "8081:8081"
    networks:
      - inception_network

  phpsysinfo:
    build:
      context: ./requirements/bonus/phpsysinfo
      dockerfile: Dockerfile
    container_name: phpsysinfo
    restart: always
    ports:
      - "8082:8082"
    networks:
      - inception_network

networks:
  inception_network:
    name: inception_network
    driver: bridge

volumes:
  mariadb_volume:
    name: mariadb_volume
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/yidemir/data/mariadb
  wordpress_volume:
    name: wordpress_volume
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/yidemir/data/wordpress

secrets:
  db_password:
    file: ../secrets/db_password.txt
  db_root_password:
    file: ../secrets/db_root_password.txt
  credentials:
    file: ../secrets/credentials.txt
  ftp_password:
    file: ../secrets/bonus/ftp_password.txt
