services:
  mariadb:
    build:
      context: ./requirements/mariadb
      dockerfile: Dockerfile
    container_name: mariadb
    restart: always
    networks:
      - inception_network
    volumes:
      - mariadb_volume:/var/lib/mysql
    secrets:
      - db_password
      - db_root_password
    env_file:
      - .env

  wordpress:
    build:
      context: ./requirements/wordpress
      dockerfile: Dockerfile
    container_name: wordpress
    restart: always
    networks:
      - inception_network
    volumes:
      - wordpress_volume:/var/www/html
    secrets:
      - db_password
      - credentials
    env_file:
      - .env

  nginx:
    build:
      context: ./requirements/nginx
      dockerfile: Dockerfile
    container_name: nginx
    restart: always
    ports:
      - "443:443"
    networks:
      - inception_network
    volumes:
      - wordpress_volume:/var/www/html
    env_file:
      - .env

networks:
  inception_network:
    name: inception_network
    driver: bridge

volumes:
  mariadb_volume:
    name: mariadb_volume
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/yidemir/data/mariadb
  wordpress_volume:
    name: wordpress_volume
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/yidemir/data/wordpress

secrets:
  db_password:
    file: ../secrets/db_password.txt
  db_root_password:
    file: ../secrets/db_root_password.txt
  credentials:
    file: ../secrets/credentials.txt
