server.document-root = "/var/www/html"
server.port = 8081

server.username = "lighttpd"
server.groupname = "lighttpd"

index-file.names = ( "index.html" )

mimetype.assign = (
  ".html" => "text/html",
  ".txt" => "text/plain",
  ".css" => "text/css",
  ".js" => "application/x-javascript",
  ".jpg" => "image/jpeg",
  ".png" => "image/png"
)
