  server {
    listen 80;
    listen 8081;
    listen 0.0.0.0:8082;
    listen 8083;
    client_max_body_size 1m;
    # error_page 404 400 403 /var/www/4xx.html;
    #error_page 500 502 503 504 /var/www/5xx.html;
	root /var/wwww/html;
    server_name localhost yidemir.42.fr;

    location / {
        allow_methods GET HEAD;
        root /var/www/html;
        index index.html;
		cgi .php /usr/bin/php-cgi;
    }

	location /assets {
		allow_methods GET;
		root /var/www/html;
		autoindex on;
	}

	location /assets/css {
		allow_methods GET;
		root /var/www/html;
	}

    location /upload {
		client_max_body_size 100;
        allow_methods POST;
        root /var/www/uploads;
        upload_dir /var/www/uploads/files;
    }

    location /cgi-bin {
        allow_methods GET POST PUT;
        root /var/www/cgi-bin;
		cgi .php /usr/bin/php-cgi;
    }

    location /redirect {
        return 301 /assets;
    }
}

server {
	listen 0.0.0.0:8084;
    client_max_body_size 1M;

    location / {
        allow_methods GET;
        root /var/www/html;
    }
}
