services:
  mariadb:
    build:
      context: ./requirements/mariadb
      dockerfile: Dockerfile
    container_name: mariadb
    restart: always
    networks:
      - webserv_network
    volumes:
      - mariadb_volume:/var/lib/mysql
    secrets:
      - db_password
      - db_root_password
    env_file:
      - .env

  webserv:
    build:
      context: ./requirements/webserv
      dockerfile: Dockerfile
    container_name: webserv
    ports:
      - "8080:8080"
    restart: always
    networks:
      - webserv_network
    volumes:
      - wordpress_volume:/var/www/html
    secrets:
      - db_password
      - credentials
    env_file:
      - .env

networks:
  webserv_network:
    name: webserv_network
    driver: bridge

volumes:
  mariadb_volume:
    name: mariadb_volume
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/yidemir/webserv/data/mariadb
  wordpress_volume:
    name: wordpress_volume
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/yidemir/webserv/data/wordpress

secrets:
  db_password:
    file: /home/yidemir/webserv/secrets/db_password.txt
  db_root_password:
    file: /home/yidemir/webserv/secrets/db_root_password.txt
  credentials:
    file: /home/yidemir/webserv/secrets/credentials.txt
