server {
	listen 80;
	root /var/www/html;
	# client_max_body_size 1m;
	location / {
		allow_methods GET;
		cgi .bla /workspace/42/webserv/tester/cgi_tester;
	}

	location /post_body {
		allow_methods POST;
		upload_dir /workspace/42/webserv/tester/post_body;
		client_max_body_size 100;
	}

	location /directory {
		allow_methods GET POST;
		root /var/www/html/YoupiBanane;
		index youpi.bad_extension;
		cgi .bla /workspace/42/webserv/tester/cgi_tester;
	}
}
