server {
	listen 127.0.0.1:8080;
	# listen 8080;
	root tester/www;
	location / {
		allow_methods GET;
		cgi .bla /sgoinfre/yidemir/42/webserv/tester/cgi_tester;
		# cgi .php /usr/bin/php-cgi;
		index index.txt;
	}

	location /post_body {
		allow_methods POST;
		upload_dir tester/post_body;
		client_max_body_size 100;
	}

	location /directory {
		allow_methods GET POST;
		root tester/www/YoupiBanane;
		index youpi.bad_extension;
		cgi .bla /sgoinfre/yidemir/42/webserv/tester/cgi_tester;
	}
}
