  server {
    listen 80;
    client_max_body_size 1M;
    error_page 404 400 413 /var/www/4xx.html;
    error_page 500 502 503 504 /var/www/5xx.html;

    location / {
        allow_methods GET;
        root /var/www/html;
        index index.html;
    }

	location /assets {
		allow_methods GET;
		root /var/www/html;
		autoindex on;
	}

	location /assets/css {
		allow_methods GET;
		root /var/www/html;
	}

    location /upload {
        allow_methods GET POST DELETE;
        root /var/www/uploads;
        upload_dir /var/www/uploads/files;
    }

    location /cgi-bin {
        allow_methods GET POST;
        root /var/www/cgi-bin;
        cgi_extension .php;
    }

    location /redirect {
        return 301 https://42.fr;
    }
}

server {
    listen 8081;
    client_max_body_size 1M;

    location / {
        allow_methods GET;
        root /var/www/html;
    }
}
