listen=YES
listen_ipv6=NO
anonymous_enable=NO
local_enable=YES
write_enable=YES
local_umask=022

guest_enable=YES
guest_username=nobody
virtual_use_local_privs=YES

dirmessage_enable=YES
xferlog_enable=YES
connect_from_port_20=YES

local_root=/var/www/html
chroot_local_user=YES
allow_writeable_chroot=YES

secure_chroot_dir=/var/empty
pam_service_name=vsftpd
seccomp_sandbox=NO

userlist_enable=YES
userlist_file=/etc/vsftpd.userlist
userlist_deny=NO
